import type { RouteRecordRaw } from 'vue-router';

export const routes: RouteRecordRaw[] = [
  {
    path: '/login',
    name: 'Login',
    component: () => import('@/views/auth/LoginView.vue'),
    meta: { layout: 'auth', public: true, title: '登录' },
  },
  {
    path: '/auth/callback',
    name: 'AuthCallback',
    component: () => import('@/views/auth/DingTalkCallbackView.vue'),
    meta: { layout: 'auth', public: true, title: '登录中' },
  },
  {
    path: '/change-password',
    name: 'ChangePassword',
    component: () => import('@/views/auth/ChangePasswordView.vue'),
    meta: { layout: 'auth', requiresAuth: true, title: '修改初始密码' },
  },
  { path: '/', redirect: '/dashboard' },
  {
    path: '/dashboard',
    name: 'Dashboard',
    component: () => import('@/views/dashboard/DashboardView.vue'),
    meta: {
      requiresAuth: true,
      title: '工作台',
      navigation: { module: 'workbench', label: '工作台', order: 10 },
    },
  },
  {
    path: '/cycles',
    name: 'Cycles',
    component: () => import('@/views/admin/CycleManageView.vue'),
    meta: {
      requiresAuth: true,
      title: '周期与计划',
      roles: ['hr', 'system_admin'],
      hrCapabilities: ['cycle_plan_edit', 'cycle_plan_review'],
      navigation: { module: 'performance', label: '周期与计划', order: 20, group: 'performance', groupLabel: '绩效运营' },
    },
  },
  {
    path: '/templates',
    name: 'Templates',
    component: () => import('@/views/admin/TemplateManageView.vue'),
    meta: {
      requiresAuth: true,
      title: '考核模板',
      roles: ['hr', 'system_admin'],
      navigation: { module: 'performance', label: '考核模板', order: 120, group: 'performance-settings', groupLabel: '绩效设置' },
    },
  },
  {
    path: '/calibration',
    name: 'Calibration',
    component: () => import('@/views/calibration/CalibrationView.vue'),
    meta: {
      requiresAuth: true,
      title: '绩效校准',
      roles: ['hr', 'system_admin'],
      navigation: { module: 'performance', label: '绩效校准', order: 30, group: 'performance', groupLabel: '绩效运营' },
    },
  },
  {
    path: '/appeals',
    name: 'Appeals',
    component: () => import('@/views/appeals/AppealsView.vue'),
    meta: {
      requiresAuth: true,
      title: '申诉管理',
      roles: ['hr', 'system_admin'],
      navigation: { module: 'performance', label: '申诉管理', order: 80, group: 'performance', groupLabel: '绩效运营' },
    },
  },
  {
    path: '/publish',
    name: 'Publish',
    component: () => import('@/views/publish/PublishView.vue'),
    meta: {
      requiresAuth: true,
      title: '结果公示',
      roles: ['hr', 'system_admin'],
      navigation: { module: 'performance', label: '结果公示', order: 70, group: 'performance', groupLabel: '绩效运营' },
    },
  },
  {
    path: '/approval',
    name: 'Approval',
    component: () => import('@/views/approval/ApprovalView.vue'),
    meta: {
      requiresAuth: true,
      title: '结果审批',
      capability: 'canViewPerformanceApproval',
      navigation: { module: 'performance', label: '结果审批', order: 60, group: 'performance', groupLabel: '绩效运营' },
    },
  },
  {
    path: '/reports',
    name: 'Reports',
    component: () => import('@/views/reports/ReportsView.vue'),
    meta: {
      requiresAuth: true,
      title: '绩效报表',
      capability: 'canViewReports',
      navigation: { module: 'performance', label: '绩效报表', order: 100, group: 'performance-analysis', groupLabel: '绩效分析' },
    },
  },
  {
    path: '/users',
    name: 'Users',
    component: () => import('@/views/admin/UserManageView.vue'),
    meta: {
      requiresAuth: true,
      title: '员工档案',
      roles: ['hr', 'system_admin'],
      hrCapabilities: ['employee_archive_edit', 'employee_archive_review', 'organization_edit'],
      navigation: { module: 'people', label: '员工档案', order: 10, group: 'people-archive', groupLabel: '人员档案' },
    },
  },
  {
    path: '/personnel-change-reviews',
    name: 'PersonnelChangeReviews',
    component: () => import('@/views/admin/PersonnelReviewView.vue'),
    meta: {
      requiresAuth: true,
      title: '人事变更审核',
      roles: ['hr', 'system_admin'],
      hrCapabilities: ['employee_archive_review'],
      navigation: { module: 'people', label: '人事变更审核', order: 20, group: 'people-archive', groupLabel: '人员档案' },
    },
  },
  {
    path: '/recruitment',
    name: 'RecruitmentOverview',
    component: () => import('@/views/recruitment/RecruitmentOverviewView.vue'),
    meta: {
      requiresAuth: true,
      title: '招聘（规划中）',
      roles: ['system_admin'],
      navigation: { module: 'recruitment', label: '招聘概览', order: 10 },
    },
  },
  {
    path: '/compensation',
    name: 'CompensationOverview',
    component: () => import('@/views/compensation/CompensationOverviewView.vue'),
    meta: {
      requiresAuth: true,
      title: '薪酬（规划中）',
      roles: ['system_admin'],
      navigation: { module: 'compensation', label: '薪酬概览', order: 10 },
    },
  },
  {
    path: '/system',
    name: 'SystemOverview',
    component: () => import('@/views/system/SystemOverviewView.vue'),
    meta: {
      requiresAuth: true,
      title: '系统管理',
      roles: ['hr', 'system_admin'],
      navigation: { module: 'system', label: '系统概览', order: 10 },
    },
  },
  {
    path: '/manager/scoring',
    name: 'ManagerScoring',
    redirect: (to) => ({ path: '/tasks', query: { ...to.query, scope: 'team', stage: 'manager-eval' } }),
    meta: {
      requiresAuth: true,
      title: '团队绩效',
      capability: 'canManageTeam',
    },
  },
  {
    path: '/interviews',
    name: 'Interviews',
    component: () => import('@/views/interview/InterviewListView.vue'),
    meta: {
      requiresAuth: true,
      title: '绩效面谈',
      capability: 'canHandleInterviews',
      navigation: { module: 'performance', label: '绩效面谈', order: 40, group: 'performance', groupLabel: '绩效运营' },
    },
  },
  {
    path: '/tasks',
    name: 'MyTasks',
    component: () => import('@/views/task/TaskListView.vue'),
    meta: {
      requiresAuth: true,
      title: '绩效工作台',
      navigation: { module: 'performance', label: '绩效工作台', order: 10, group: 'performance-workbench', groupLabel: '绩效工作台' },
    },
  },
  {
    path: '/tasks/:id',
    name: 'TaskDetail',
    component: () => import('@/views/task/TaskDetailView.vue'),
    meta: { requiresAuth: true, title: '任务详情' },
  },
  {
    path: '/improvement-plans',
    name: 'ImprovementPlans',
    component: () => import('@/views/improvement-plans/ImprovementPlanListView.vue'),
    meta: {
      requiresAuth: true,
      title: '改进计划',
      navigation: { module: 'performance', label: '改进计划', order: 50, group: 'performance', groupLabel: '绩效运营' },
    },
  },
  {
    path: '/improvement-plans/:id',
    name: 'ImprovementPlanDetail',
    component: () => import('@/views/improvement-plans/ImprovementPlanDetailView.vue'),
    meta: { requiresAuth: true, title: '改进计划详情' },
  },
  {
    path: '/probation-reviews/manage',
    name: 'ProbationManage',
    component: () => import('@/views/probation/ProbationManageView.vue'),
    meta: {
      requiresAuth: true,
      title: '试用期考核管理',
      roles: ['hr', 'system_admin'],
      navigation: { module: 'performance', label: '试用期考核管理', order: 130, group: 'performance-probation', groupLabel: '试用期与转正' },
    },
  },
  {
    path: '/probation-reviews/manager',
    name: 'ProbationManager',
    component: () => import('@/views/probation/ProbationManagerView.vue'),
    meta: {
      requiresAuth: true,
      title: '试用期评分',
      capability: 'canHandleProbationReviews',
      navigation: { module: 'performance', label: '试用期评分', order: 140, group: 'performance-probation', groupLabel: '试用期与转正' },
    },
  },
  {
    path: '/probation-reviews/mine',
    name: 'ProbationMine',
    component: () => import('@/views/probation/ProbationMineView.vue'),
    meta: {
      requiresAuth: true,
      title: '我的试用期考核',
      navigation: { module: 'performance', label: '我的试用期考核', order: 150, group: 'performance-probation', groupLabel: '试用期与转正' },
    },
  },
  {
    path: '/probation-reviews/:id',
    name: 'ProbationDetail',
    component: () => import('@/views/probation/ProbationDetailView.vue'),
    meta: { requiresAuth: true, title: '试用期考核详情' },
  },
  {
    path: '/confirmation-applications/manage',
    name: 'ConfirmationManage',
    component: () => import('@/views/confirmation/ConfirmationManageView.vue'),
    meta: {
      requiresAuth: true,
      title: '转正申请管理',
      roles: ['hr', 'system_admin'],
      navigation: { module: 'performance', label: '转正申请管理', order: 160, group: 'performance-probation', groupLabel: '试用期与转正' },
    },
  },
  {
    path: '/confirmation-applications/approvals',
    name: 'ConfirmationApprovals',
    component: () => import('@/views/confirmation/ConfirmationApprovalView.vue'),
    meta: {
      requiresAuth: true,
      title: '转正审批台',
      capability: 'canHandleConfirmationApprovals',
      navigation: { module: 'performance', label: '转正审批台', order: 170, group: 'performance-probation', groupLabel: '试用期与转正' },
    },
  },
  {
    path: '/confirmation-applications/mine',
    name: 'ConfirmationMine',
    component: () => import('@/views/confirmation/ConfirmationMineView.vue'),
    meta: {
      requiresAuth: true,
      title: '我的转正申请',
      navigation: { module: 'performance', label: '我的转正申请', order: 180, group: 'performance-probation', groupLabel: '试用期与转正' },
    },
  },
  {
    path: '/confirmation-applications/:id',
    name: 'ConfirmationDetail',
    component: () => import('@/views/confirmation/ConfirmationDetailView.vue'),
    meta: { requiresAuth: true, title: '转正申请详情' },
  },
  {
    path: '/objectives',
    name: 'ObjectiveMap',
    component: () => import('@/views/objectives/ObjectiveMapView.vue'),
    meta: { requiresAuth: true, title: '目标地图', activeNavigationPath: '/tasks' },
  },
  {
    path: '/action-items',
    name: 'ActionItems',
    component: () => import('@/views/objectives/GoalTrackingView.vue'),
    meta: { requiresAuth: true, title: '目标跟进', activeNavigationPath: '/tasks' },
  },
  {
    path: '/:pathMatch(.*)*',
    name: 'NotFound',
    component: () => import('@/views/NotFoundView.vue'),
    meta: { layout: 'auth', public: true },
  },
];
