import type { RouteRecordRaw } from 'vue-router';

export const routes: RouteRecordRaw[] = [
  {
    path: '/login',
    name: 'Login',
    component: () => import('@/views/auth/LoginView.vue'),
    meta: { layout: 'auth', public: true, title: '登录' },
  },
  {
    path: '/auth/callback',
    name: 'AuthCallback',
    component: () => import('@/views/auth/DingTalkCallbackView.vue'),
    meta: { layout: 'auth', public: true, title: '登录中' },
  },
  { path: '/', redirect: '/dashboard' },
  {
    path: '/dashboard',
    name: 'Dashboard',
    component: () => import('@/views/dashboard/DashboardView.vue'),
    meta: {
      requiresAuth: true,
      title: '工作台',
      navigation: { module: 'workbench', label: '工作台', order: 10 },
    },
  },
  {
    path: '/cycles',
    name: 'Cycles',
    component: () => import('@/views/admin/CycleManageView.vue'),
    meta: {
      requiresAuth: true,
      title: '周期与计划',
      roles: ['hr', 'system_admin'],
      navigation: { module: 'performance', label: '周期与计划', order: 20, group: 'performance', groupLabel: '绩效管理' },
    },
  },
  {
    path: '/templates',
    name: 'Templates',
    component: () => import('@/views/admin/TemplateManageView.vue'),
    meta: {
      requiresAuth: true,
      title: '考核模板',
      roles: ['hr', 'system_admin'],
      navigation: { module: 'analysis', label: '考核模板', order: 30, group: 'indicator-config', groupLabel: '指标与模板' },
    },
  },
  {
    path: '/indicators',
    name: 'IndicatorLibrary',
    component: () => import('@/views/admin/IndicatorLibraryView.vue'),
    meta: {
      requiresAuth: true,
      title: '指标库',
      roles: ['hr', 'system_admin'],
      navigation: { module: 'analysis', label: '指标库', order: 20, group: 'indicator-config', groupLabel: '指标与模板' },
    },
  },
  {
    path: '/calibration',
    name: 'Calibration',
    component: () => import('@/views/calibration/CalibrationView.vue'),
    meta: {
      requiresAuth: true,
      title: '绩效校准',
      roles: ['hr', 'system_admin'],
      navigation: { module: 'performance', label: '绩效校准', order: 30, group: 'performance', groupLabel: '绩效管理' },
    },
  },
  {
    path: '/appeals',
    name: 'Appeals',
    component: () => import('@/views/appeals/AppealsView.vue'),
    meta: {
      requiresAuth: true,
      title: '申诉管理',
      roles: ['hr', 'system_admin'],
      navigation: { module: 'performance', label: '申诉管理', order: 80, group: 'performance', groupLabel: '绩效管理' },
    },
  },
  {
    path: '/publish',
    name: 'Publish',
    component: () => import('@/views/publish/PublishView.vue'),
    meta: {
      requiresAuth: true,
      title: '结果公示',
      roles: ['hr', 'system_admin'],
      navigation: { module: 'performance', label: '结果公示', order: 70, group: 'performance', groupLabel: '绩效管理' },
    },
  },
  {
    path: '/approval',
    name: 'Approval',
    component: () => import('@/views/approval/ApprovalView.vue'),
    meta: {
      requiresAuth: true,
      title: '结果审批',
      capability: 'canViewPerformanceApproval',
      navigation: { module: 'performance', label: '结果审批', order: 60, group: 'performance', groupLabel: '绩效管理' },
    },
  },
  {
    path: '/reports',
    name: 'Reports',
    component: () => import('@/views/reports/ReportsView.vue'),
    meta: {
      requiresAuth: true,
      title: '报表分析',
      capability: 'canViewReports',
      navigation: { module: 'analysis', label: '报表分析', order: 10 },
    },
  },
  {
    path: '/users',
    name: 'Users',
    component: () => import('@/views/admin/UserManageView.vue'),
    meta: {
      requiresAuth: true,
      title: '员工档案',
      roles: ['hr', 'system_admin'],
      navigation: { module: 'analysis', label: '员工档案', order: 40 },
    },
  },
  {
    path: '/manager/scoring',
    name: 'ManagerScoring',
    redirect: (to) => ({ path: '/tasks', query: { ...to.query, scope: 'team', stage: 'manager-eval' } }),
    meta: {
      requiresAuth: true,
      title: '团队绩效',
      capability: 'canManageTeam',
    },
  },
  {
    path: '/interviews',
    name: 'Interviews',
    component: () => import('@/views/interview/InterviewListView.vue'),
    meta: {
      requiresAuth: true,
      title: '绩效面谈',
      capability: 'canHandleInterviews',
      navigation: { module: 'performance', label: '绩效面谈', order: 40, group: 'performance', groupLabel: '绩效管理' },
    },
  },
  {
    path: '/tasks',
    name: 'MyTasks',
    component: () => import('@/views/task/TaskListView.vue'),
    meta: {
      requiresAuth: true,
      title: '绩效工作台',
      navigation: { module: 'performance', label: '绩效工作台', order: 10, group: 'performance', groupLabel: '绩效管理' },
    },
  },
  {
    path: '/tasks/:id',
    name: 'TaskDetail',
    component: () => import('@/views/task/TaskDetailView.vue'),
    meta: { requiresAuth: true, title: '任务详情' },
  },
  {
    path: '/improvement-plans',
    name: 'ImprovementPlans',
    component: () => import('@/views/improvement-plans/ImprovementPlanListView.vue'),
    meta: {
      requiresAuth: true,
      title: '改进计划',
      navigation: { module: 'performance', label: '改进计划', order: 50, group: 'performance', groupLabel: '绩效管理' },
    },
  },
  {
    path: '/improvement-plans/:id',
    name: 'ImprovementPlanDetail',
    component: () => import('@/views/improvement-plans/ImprovementPlanDetailView.vue'),
    meta: { requiresAuth: true, title: '改进计划详情' },
  },
  {
    path: '/probation-reviews/manage',
    name: 'ProbationManage',
    component: () => import('@/views/probation/ProbationManageView.vue'),
    meta: {
      requiresAuth: true,
      title: '试用期考核管理',
      roles: ['hr', 'system_admin'],
      navigation: { module: 'people', label: '试用期考核管理', order: 10, group: 'people', groupLabel: '试用期与转正' },
    },
  },
  {
    path: '/probation-reviews/manager',
    name: 'ProbationManager',
    component: () => import('@/views/probation/ProbationManagerView.vue'),
    meta: {
      requiresAuth: true,
      title: '试用期评分',
      capability: 'canHandleProbationReviews',
      navigation: { module: 'people', label: '试用期评分', order: 20, group: 'people', groupLabel: '试用期与转正' },
    },
  },
  {
    path: '/probation-reviews/mine',
    name: 'ProbationMine',
    component: () => import('@/views/probation/ProbationMineView.vue'),
    meta: {
      requiresAuth: true,
      title: '我的试用期考核',
      navigation: { module: 'people', label: '我的试用期考核', order: 30, group: 'people', groupLabel: '试用期与转正' },
    },
  },
  {
    path: '/probation-reviews/:id',
    name: 'ProbationDetail',
    component: () => import('@/views/probation/ProbationDetailView.vue'),
    meta: { requiresAuth: true, title: '试用期考核详情' },
  },
  {
    path: '/confirmation-applications/manage',
    name: 'ConfirmationManage',
    component: () => import('@/views/confirmation/ConfirmationManageView.vue'),
    meta: {
      requiresAuth: true,
      title: '转正申请管理',
      roles: ['hr', 'system_admin'],
      navigation: { module: 'people', label: '转正申请管理', order: 40, group: 'people', groupLabel: '试用期与转正' },
    },
  },
  {
    path: '/confirmation-applications/approvals',
    name: 'ConfirmationApprovals',
    component: () => import('@/views/confirmation/ConfirmationApprovalView.vue'),
    meta: {
      requiresAuth: true,
      title: '转正审批台',
      capability: 'canHandleConfirmationApprovals',
      navigation: { module: 'people', label: '转正审批台', order: 50, group: 'people', groupLabel: '试用期与转正' },
    },
  },
  {
    path: '/confirmation-applications/mine',
    name: 'ConfirmationMine',
    component: () => import('@/views/confirmation/ConfirmationMineView.vue'),
    meta: {
      requiresAuth: true,
      title: '我的转正申请',
      navigation: { module: 'people', label: '我的转正申请', order: 60, group: 'people', groupLabel: '试用期与转正' },
    },
  },
  {
    path: '/confirmation-applications/:id',
    name: 'ConfirmationDetail',
    component: () => import('@/views/confirmation/ConfirmationDetailView.vue'),
    meta: { requiresAuth: true, title: '转正申请详情' },
  },
  {
    path: '/objectives',
    name: 'ObjectiveMap',
    component: () => import('@/views/objectives/ObjectiveMapView.vue'),
    meta: { requiresAuth: true, title: '目标地图' },
  },
  {
    path: '/action-items',
    name: 'ActionItems',
    component: () => import('@/views/objectives/GoalTrackingView.vue'),
    meta: { requiresAuth: true, title: '目标跟进' },
  },
  {
    path: '/:pathMatch(.*)*',
    name: 'NotFound',
    component: () => import('@/views/NotFoundView.vue'),
    meta: { layout: 'auth', public: true },
  },
];
