import { IndicatorType, Prisma, PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

type IndicatorSeed = {
  name: string;
  code: string;
  category: string;
  groupName: string;
  description: string;
  scoringStandard: string;
  dataSource: string;
  dataCaliber: string;
  targetValue?: number;
  unit?: string;
  type?: IndicatorType;
};

const indicators: IndicatorSeed[] = [
  {
    name: '季度销售回款达成率',
    code: 'KPI-SALES-COLLECTION-Q',
    category: '经营结果',
    groupName: '销售部',
    description: '衡量季度实际回款金额相对计划回款金额的完成情况。',
    scoringStandard: '实际回款金额 / 计划回款金额 * 100%，低于 80% 需说明原因。',
    dataSource: '财务回款台账',
    dataCaliber: '以财务确认入账日期为准，剔除内部往来与退款冲正。',
    targetValue: 100,
    unit: '%',
  },
  {
    name: 'B2B重点客户成交额',
    code: 'KPI-SALES-B2B-GMV',
    category: '经营结果',
    groupName: 'B2B销售组',
    description: '衡量 B2B 重点客户季度成交规模。',
    scoringStandard: '季度重点客户确认成交额达到目标值为满分，按完成率线性折算。',
    dataSource: '销售订单系统',
    dataCaliber: '按已确认订单含税金额统计，取消订单和退货订单不计入。',
    targetValue: 300,
    unit: '万元',
  },
  {
    name: '线下门店销售达成率',
    code: 'KPI-SALES-RETAIL-ACH',
    category: '经营结果',
    groupName: '线下零售组',
    description: '衡量线下零售门店销售目标完成情况。',
    scoringStandard: '实际销售额 / 目标销售额 * 100%。',
    dataSource: '门店 POS 系统',
    dataCaliber: '按自然月汇总，剔除退货和内部调拨。',
    targetValue: 100,
    unit: '%',
  },
  {
    name: '新客户有效开发数',
    code: 'KPI-SALES-NEW-CUSTOMERS',
    category: '客户增长',
    groupName: '销售部',
    description: '衡量销售团队新增有效客户开发情况。',
    scoringStandard: '完成目标客户数为满分，有效客户需完成首单或签署合作协议。',
    dataSource: 'CRM 客户管理系统',
    dataCaliber: '同一主体客户去重，试单金额低于门槛的不计入。',
    targetValue: 10,
    unit: '家',
  },
  {
    name: '采购准交率',
    code: 'KPI-SC-PO-ONTIME',
    category: '供应链履约',
    groupName: '供应链管理部',
    description: '衡量供应商按采购交期准时到货的比例。',
    scoringStandard: '准时到货采购单行数 / 应到货采购单行数 * 100%。',
    dataSource: '采购管理系统',
    dataCaliber: '以仓库收货时间为准，供应商原因延期计入未准交。',
    targetValue: 95,
    unit: '%',
  },
  {
    name: '库存周转天数',
    code: 'KPI-SC-INVENTORY-DAYS',
    category: '库存管理',
    groupName: '供应链中心',
    description: '衡量库存占用和周转效率。',
    scoringStandard: '库存周转天数低于目标值为满分，超出部分按规则扣分。',
    dataSource: 'ERP 库存报表',
    dataCaliber: '按月均库存金额 / 月销售成本 * 当月天数计算。',
    targetValue: 45,
    unit: '天',
  },
  {
    name: '仓储发货准确率',
    code: 'KPI-SC-WAREHOUSE-ACCURACY',
    category: '仓储履约',
    groupName: '仓储定制部',
    description: '衡量仓储拣货、包装、发货准确性。',
    scoringStandard: '准确发货单数 / 总发货单数 * 100%。',
    dataSource: 'WMS 仓储系统',
    dataCaliber: '客户投诉、复核差异、错漏发均计为不准确。',
    targetValue: 99,
    unit: '%',
  },
  {
    name: '外贸订单按期交付率',
    code: 'KPI-SC-FOREIGN-ONTIME',
    category: '供应链履约',
    groupName: '外贸组',
    description: '衡量外贸订单按客户确认交期完成出运的比例。',
    scoringStandard: '按期出运订单数 / 应出运订单数 * 100%。',
    dataSource: '外贸订单台账',
    dataCaliber: '以报关或物流提单日期为准，客户变更交期需有记录。',
    targetValue: 95,
    unit: '%',
  },
  {
    name: '项目节点按期达成率',
    code: 'KPI-PROJECT-MILESTONE-ONTIME',
    category: '项目交付',
    groupName: '项目中心',
    description: '衡量项目关键里程碑按计划完成情况。',
    scoringStandard: '按期完成节点数 / 应完成节点数 * 100%。',
    dataSource: '项目计划表',
    dataCaliber: '以项目经理确认的基准计划为准，延期需记录原因。',
    targetValue: 90,
    unit: '%',
  },
  {
    name: '项目毛利率',
    code: 'KPI-PROJECT-GROSS-MARGIN',
    category: '经营结果',
    groupName: '项目中心',
    description: '衡量项目收入扣除直接成本后的盈利水平。',
    scoringStandard: '实际项目毛利率达到目标值为满分。',
    dataSource: '项目损益表',
    dataCaliber: '按项目维度归集收入、采购、物流、外包等直接成本。',
    targetValue: 25,
    unit: '%',
  },
  {
    name: '项目变更闭环及时率',
    code: 'KPI-PROJECT-CHANGE-CLOSE',
    category: '项目管理',
    groupName: '项目管理和运营部',
    description: '衡量项目变更事项在规定时限内完成确认和闭环。',
    scoringStandard: '及时闭环变更数 / 变更总数 * 100%。',
    dataSource: '项目变更台账',
    dataCaliber: '以客户/内部审批完成时间为准，重复变更合并统计。',
    targetValue: 95,
    unit: '%',
  },
  {
    name: '门店活动落地完成率',
    code: 'KPI-STORE-CAMPAIGN-EXEC',
    category: '门店运营',
    groupName: '北京国安世茂工三店',
    description: '衡量门店营销活动物料、陈列、人员执行到位情况。',
    scoringStandard: '按活动检查清单完成项 / 应完成项 * 100%。',
    dataSource: '门店巡检记录',
    dataCaliber: '按活动周期统计，逾期整改项按未完成计。',
    targetValue: 98,
    unit: '%',
  },
  {
    name: '门店会员复购率',
    code: 'KPI-STORE-MEMBER-REPURCHASE',
    category: '客户增长',
    groupName: '浙江FC黄龙店',
    description: '衡量门店会员二次及以上消费占比。',
    scoringStandard: '复购会员数 / 有消费会员数 * 100%。',
    dataSource: '会员系统',
    dataCaliber: '同一会员自然季度内多次购买计为复购。',
    targetValue: 35,
    unit: '%',
  },
  {
    name: '直播 GMV 达成率',
    code: 'KPI-LIVE-GMV-ACH',
    category: '电商运营',
    groupName: '直播电商部',
    description: '衡量直播电商销售额目标达成情况。',
    scoringStandard: '直播成交 GMV / 目标 GMV * 100%。',
    dataSource: '直播平台后台',
    dataCaliber: '按支付 GMV 统计，剔除退款、刷单和异常订单。',
    targetValue: 100,
    unit: '%',
  },
  {
    name: '直播间转化率',
    code: 'KPI-LIVE-CONVERSION',
    category: '电商运营',
    groupName: '直播电商部',
    description: '衡量直播间观看用户转化为下单用户的效率。',
    scoringStandard: '下单人数 / 进入直播间人数 * 100%。',
    dataSource: '直播平台数据中心',
    dataCaliber: '按单场直播统计，去除异常流量。',
    targetValue: 6,
    unit: '%',
  },
  {
    name: '客服首次响应及时率',
    code: 'KPI-CS-FIRST-RESPONSE',
    category: '客户服务',
    groupName: '客服部',
    description: '衡量客服在标准时限内首次响应客户咨询的比例。',
    scoringStandard: '及时首次响应会话数 / 总会话数 * 100%。',
    dataSource: '客服工单系统',
    dataCaliber: '工作时间内超过 60 秒未响应计为不及时。',
    targetValue: 95,
    unit: '%',
  },
  {
    name: '客户投诉闭环率',
    code: 'KPI-CS-COMPLAINT-CLOSE',
    category: '客户服务',
    groupName: '客服部',
    description: '衡量客户投诉在规定时间内处理完成并闭环的比例。',
    scoringStandard: '按期闭环投诉数 / 投诉总数 * 100%。',
    dataSource: '客服工单系统',
    dataCaliber: '以客户确认或主管复核完成作为闭环。',
    targetValue: 98,
    unit: '%',
  },
  {
    name: '设计需求按期交付率',
    code: 'KPI-DESIGN-ONTIME',
    category: '创意设计',
    groupName: '创意设计部',
    description: '衡量设计需求按排期完成交付的比例。',
    scoringStandard: '按期交付需求数 / 应交付需求数 * 100%。',
    dataSource: '设计需求看板',
    dataCaliber: '需求范围变更需重新确认交期，否则按原交期统计。',
    targetValue: 92,
    unit: '%',
  },
  {
    name: '视觉素材一次通过率',
    code: 'KPI-DESIGN-FIRST-PASS',
    category: '创意设计',
    groupName: '视觉设计部',
    description: '衡量视觉素材首轮评审通过质量。',
    scoringStandard: '一次通过素材数 / 提交素材总数 * 100%。',
    dataSource: '设计评审记录',
    dataCaliber: '因需求方改 brief 导致返工不计入未通过。',
    targetValue: 85,
    unit: '%',
  },
  {
    name: '短视频素材产出完成率',
    code: 'KPI-VIDEO-OUTPUT-ACH',
    category: '创意设计',
    groupName: '视觉视频组',
    description: '衡量短视频素材按计划产出的完成情况。',
    scoringStandard: '实际交付条数 / 计划交付条数 * 100%。',
    dataSource: '内容排期表',
    dataCaliber: '仅统计通过发布审核的成片素材。',
    targetValue: 100,
    unit: '%',
  },
  {
    name: '系统需求按期上线率',
    code: 'KPI-DIGITAL-RELEASE-ONTIME',
    category: '数字化运营',
    groupName: '数字化运营部',
    description: '衡量内部系统需求按计划上线的比例。',
    scoringStandard: '按期上线需求数 / 应上线需求数 * 100%。',
    dataSource: '研发需求管理平台',
    dataCaliber: '以上线到生产环境并验收通过为准。',
    targetValue: 90,
    unit: '%',
  },
  {
    name: '关键系统可用率',
    code: 'KPI-DIGITAL-SLA',
    category: '数字化运营',
    groupName: '数字化运营部',
    description: '衡量关键业务系统稳定运行水平。',
    scoringStandard: '可用时长 / 统计周期总时长 * 100%。',
    dataSource: '系统监控平台',
    dataCaliber: '计划内维护窗口不计入不可用时长。',
    targetValue: 99.5,
    unit: '%',
  },
  {
    name: '研发缺陷修复及时率',
    code: 'KPI-RD-BUG-FIX-ONTIME',
    category: '研发质量',
    groupName: '研发部',
    description: '衡量研发缺陷在 SLA 内修复的比例。',
    scoringStandard: 'SLA 内修复缺陷数 / 应修复缺陷数 * 100%。',
    dataSource: '缺陷管理平台',
    dataCaliber: '按缺陷等级设置不同 SLA，重复缺陷合并统计。',
    targetValue: 95,
    unit: '%',
  },
  {
    name: '运营活动 ROI',
    code: 'KPI-OPS-CAMPAIGN-ROI',
    category: '运营增长',
    groupName: '运营部',
    description: '衡量运营活动投入产出效果。',
    scoringStandard: '活动带来毛利 / 活动投入费用，达到目标值为满分。',
    dataSource: '运营活动复盘表',
    dataCaliber: '活动收入按归因周期统计，费用含投放、物料和优惠成本。',
    targetValue: 1.5,
    unit: '倍',
  },
  {
    name: '运营任务闭环及时率',
    code: 'KPI-OPS-TASK-CLOSE',
    category: '运营管理',
    groupName: '运营部',
    description: '衡量运营动作在承诺时限内完成闭环的比例。',
    scoringStandard: '按期闭环任务数 / 应闭环任务数 * 100%。',
    dataSource: '运营任务看板',
    dataCaliber: '延期任务需有审批记录，否则计入未按期。',
    targetValue: 95,
    unit: '%',
  },
  {
    name: '招聘岗位按期到岗率',
    code: 'KPI-HR-HIRING-ONTIME',
    category: '人力资源',
    groupName: '人事部',
    description: '衡量关键招聘岗位在计划时间内完成到岗的比例。',
    scoringStandard: '按期到岗岗位数 / 招聘需求岗位数 * 100%。',
    dataSource: '招聘需求台账',
    dataCaliber: '以候选人实际入职日期为准，需求暂停岗位不计入。',
    targetValue: 90,
    unit: '%',
  },
  {
    name: '员工试用期转正按期完成率',
    code: 'KPI-HR-PROBATION-CLOSE',
    category: '人力资源',
    groupName: '人力资源部',
    description: '衡量员工试用期考核和转正流程按期完成情况。',
    scoringStandard: '按期完成转正流程人数 / 应完成转正人数 * 100%。',
    dataSource: '人事系统',
    dataCaliber: '以转正审批完成日期为准，延期需有审批记录。',
    targetValue: 98,
    unit: '%',
  },
  {
    name: '行政事项响应及时率',
    code: 'KPI-ADMIN-RESPONSE',
    category: '行政服务',
    groupName: '行政部',
    description: '衡量行政支持事项在承诺时限内响应和处理的比例。',
    scoringStandard: '按期响应事项数 / 行政事项总数 * 100%。',
    dataSource: '行政服务台账',
    dataCaliber: '按员工提交时间和首次处理时间计算。',
    targetValue: 95,
    unit: '%',
  },
  {
    name: '费用报销审核及时率',
    code: 'KPI-FIN-REIMBURSE-ONTIME',
    category: '财务管理',
    groupName: '财务部',
    description: '衡量费用报销单据在规定时限内完成财务审核的比例。',
    scoringStandard: '按期审核单据数 / 应审核单据数 * 100%。',
    dataSource: '财务报销系统',
    dataCaliber: '退回补充材料的单据按重新提交时间计算。',
    targetValue: 95,
    unit: '%',
  },
  {
    name: '月度结账准时率',
    code: 'KPI-FIN-CLOSE-ONTIME',
    category: '财务管理',
    groupName: '财务部',
    description: '衡量月度财务结账按计划完成情况。',
    scoringStandard: '按期完成结账月份数 / 应结账月份数 * 100%。',
    dataSource: '财务总账系统',
    dataCaliber: '以财务负责人确认结账完成时间为准。',
    targetValue: 100,
    unit: '%',
  },
  {
    name: '管理决策事项推进完成率',
    code: 'KPI-GMO-DECISION-CLOSE',
    category: '经营管理',
    groupName: '总经办',
    description: '衡量总经办跟进的重点决策事项推进闭环情况。',
    scoringStandard: '已闭环事项数 / 到期应闭环事项数 * 100%。',
    dataSource: '经营会议纪要',
    dataCaliber: '以会议纪要明确责任人和完成时限的事项为统计范围。',
    targetValue: 95,
    unit: '%',
  },
  {
    name: '创新项目验证达成率',
    code: 'KPI-INNOVATION-VALIDATION',
    category: '创新业务',
    groupName: '创新业务中心',
    description: '衡量创新业务项目按阶段完成验证目标的比例。',
    scoringStandard: '完成阶段验证项目数 / 应验证项目数 * 100%。',
    dataSource: '创新项目台账',
    dataCaliber: '验证目标需包含样品、客户反馈、试销或商业测算结果。',
    targetValue: 80,
    unit: '%',
  },
  {
    name: '外援任务交付验收通过率',
    code: 'KPI-OUTSOURCE-ACCEPTANCE',
    category: '外援管理',
    groupName: '外援',
    description: '衡量外援团队交付任务的一次验收通过情况。',
    scoringStandard: '一次验收通过任务数 / 提交验收任务数 * 100%。',
    dataSource: '外援任务台账',
    dataCaliber: '返工后通过不计入一次通过。',
    targetValue: 90,
    unit: '%',
  },
  {
    name: '吉客云数据同步成功率',
    code: 'KPI-JKY-SYNC-SUCCESS',
    category: '系统运维',
    groupName: '吉客云系统外援',
    description: '衡量吉客云相关数据接口同步成功情况。',
    scoringStandard: '成功同步批次数 / 应同步批次数 * 100%。',
    dataSource: '接口同步日志',
    dataCaliber: '按日批次统计，业务方取消同步任务不计入。',
    targetValue: 99,
    unit: '%',
  },
  {
    name: '协泰外援交付及时率',
    code: 'KPI-XIETAI-DELIVERY-ONTIME',
    category: '外援管理',
    groupName: '协泰外援',
    description: '衡量协泰外援任务按约定时间交付情况。',
    scoringStandard: '按期交付任务数 / 应交付任务数 * 100%。',
    dataSource: '外援协作台账',
    dataCaliber: '以业务负责人验收确认时间为准。',
    targetValue: 95,
    unit: '%',
  },
];

async function main() {
  const hr = await prisma.user.findUnique({ where: { employeeNo: 'HR001' }, select: { id: true } });

  for (const item of indicators) {
    await prisma.indicator.upsert({
      where: { code: item.code },
      update: {
        name: item.name,
        category: item.category,
        type: item.type ?? IndicatorType.kpi,
        description: item.description,
        scoringStandard: item.scoringStandard,
        dataSource: item.dataSource,
        dataCaliber: item.dataCaliber,
        targetValue: item.targetValue != null ? new Prisma.Decimal(item.targetValue) : null,
        unit: item.unit ?? null,
        groupName: item.groupName,
        isActive: true,
      },
      create: {
        name: item.name,
        code: item.code,
        category: item.category,
        type: item.type ?? IndicatorType.kpi,
        description: item.description,
        scoringStandard: item.scoringStandard,
        dataSource: item.dataSource,
        dataCaliber: item.dataCaliber,
        targetValue: item.targetValue != null ? new Prisma.Decimal(item.targetValue) : undefined,
        unit: item.unit,
        groupName: item.groupName,
        isActive: true,
        ...(hr ? { creator: { connect: { id: hr.id } } } : {}),
      },
    });
  }

  console.log(`已写入/更新 ${indicators.length} 个真实业务指标`);
}

main()
  .catch((error) => {
    console.error('写入真实业务指标失败：', error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
